[package]
name = "functions_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "functions_rs"
path = "focusfeedbackgui/functions.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module", "abi3-py38", "generate-import-lib"] }
ndarray = { version = "0.15.6", features = ["approx", "rayon"] }
numpy = "0.18.0"
statrs = "0.16.0"

[package.metadata.maturin]
name = "focusfeedbackgui.functions_rs"