from numpy import ndarray

def meshgrid(x: ndarray, y: ndarray) -> ndarray: ...

def gaussian7grid(p: ndarray, xv: ndarray, yv: ndarray) -> ndarray: ...

def gaussian(p: ndarray, x: int, y: int) -> ndarray: ...
